"""auto migration

Revision ID: 353f5cfbd1b5
Revises: 8c2d8c824640
Create Date: 2025-03-10 16:00:01.946925

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '353f5cfbd1b5'
down_revision: Union[str, None] = '8c2d8c824640'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_user_id', table_name='users')
    op.create_index(op.f('ix_users_user_id'), 'users', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_user_id'), table_name='users')
    op.create_index('ix_users_user_id', 'users', ['user_id'], unique=False)
    # ### end Alembic commands ###
