"""auto migration

Revision ID: 3b0071faf4e8
Revises: 4c5199efaf04
Create Date: 2025-03-10 16:20:20.419223

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '3b0071faf4e8'
down_revision: Union[str, None] = '4c5199efaf04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'create_time',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('users', 'update_time',
               existing_type=mysql.DATETIME(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'update_time',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('users', 'create_time',
               existing_type=mysql.DATETIME(),
               nullable=True)
    # ### end Alembic commands ###
