"""auto migration

Revision ID: 4e9b0c59d1b1
Revises: 9cc952e6a3d0
Create Date: 2025-03-12 15:54:53.770124

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e9b0c59d1b1'
down_revision: Union[str, None] = '9cc952e6a3d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wx_msg_subscribe_template', sa.Column('miniprogram_state', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_wx_msg_subscribe_template_miniprogram_state'), 'wx_msg_subscribe_template', ['miniprogram_state'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wx_msg_subscribe_template_miniprogram_state'), table_name='wx_msg_subscribe_template')
    op.drop_column('wx_msg_subscribe_template', 'miniprogram_state')
    # ### end Alembic commands ###
