"""auto migration

Revision ID: 5276401e84bd
Revises: 
Create Date: 2025-03-13 19:40:26.483739

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5276401e84bd'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test2',
    sa.Column('test2_id', sa.Integer(), nullable=False),
    sa.Column('test2_name', sa.String(length=50), nullable=True),
    sa.Column('test2_age', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('test2_id')
    )
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.Column('openid', sa.String(length=50), nullable=False),
    sa.Column('session_key', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('user_avatar_pic', sa.String(length=255), nullable=True),
    sa.Column('user_address', sa.String(length=255), nullable=True),
    sa.Column('user_role', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('openid')
    )
    op.create_index(op.f('ix_users_user_id'), 'users', ['user_id'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('wx_msg_subscribe_template',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entry', sa.String(length=50), nullable=False),
    sa.Column('template_id', sa.String(length=50), nullable=False),
    sa.Column('template_name', sa.String(length=255), nullable=False),
    sa.Column('template_content', sa.String(length=255), nullable=False),
    sa.Column('page', sa.String(length=255), nullable=False),
    sa.Column('miniprogram_state', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wx_msg_subscribe_template_entry'), 'wx_msg_subscribe_template', ['entry'], unique=False)
    op.create_index(op.f('ix_wx_msg_subscribe_template_id'), 'wx_msg_subscribe_template', ['id'], unique=True)
    op.create_index(op.f('ix_wx_msg_subscribe_template_miniprogram_state'), 'wx_msg_subscribe_template', ['miniprogram_state'], unique=False)
    op.create_index(op.f('ix_wx_msg_subscribe_template_page'), 'wx_msg_subscribe_template', ['page'], unique=False)
    op.create_index(op.f('ix_wx_msg_subscribe_template_template_content'), 'wx_msg_subscribe_template', ['template_content'], unique=False)
    op.create_index(op.f('ix_wx_msg_subscribe_template_template_id'), 'wx_msg_subscribe_template', ['template_id'], unique=False)
    op.create_index(op.f('ix_wx_msg_subscribe_template_template_name'), 'wx_msg_subscribe_template', ['template_name'], unique=False)
    op.create_table('wx_msg_subscribe_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('openid', sa.String(length=50), nullable=True),
    sa.Column('template_id', sa.String(length=50), nullable=False),
    sa.Column('subscribe_status', sa.String(length=50), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wx_msg_subscribe_user_id'), 'wx_msg_subscribe_user', ['id'], unique=True)
    op.create_index(op.f('ix_wx_msg_subscribe_user_openid'), 'wx_msg_subscribe_user', ['openid'], unique=True)
    op.create_index(op.f('ix_wx_msg_subscribe_user_subscribe_status'), 'wx_msg_subscribe_user', ['subscribe_status'], unique=False)
    op.create_index(op.f('ix_wx_msg_subscribe_user_template_id'), 'wx_msg_subscribe_user', ['template_id'], unique=False)
    op.create_index(op.f('ix_wx_msg_subscribe_user_user_id'), 'wx_msg_subscribe_user', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wx_msg_subscribe_user_user_id'), table_name='wx_msg_subscribe_user')
    op.drop_index(op.f('ix_wx_msg_subscribe_user_template_id'), table_name='wx_msg_subscribe_user')
    op.drop_index(op.f('ix_wx_msg_subscribe_user_subscribe_status'), table_name='wx_msg_subscribe_user')
    op.drop_index(op.f('ix_wx_msg_subscribe_user_openid'), table_name='wx_msg_subscribe_user')
    op.drop_index(op.f('ix_wx_msg_subscribe_user_id'), table_name='wx_msg_subscribe_user')
    op.drop_table('wx_msg_subscribe_user')
    op.drop_index(op.f('ix_wx_msg_subscribe_template_template_name'), table_name='wx_msg_subscribe_template')
    op.drop_index(op.f('ix_wx_msg_subscribe_template_template_id'), table_name='wx_msg_subscribe_template')
    op.drop_index(op.f('ix_wx_msg_subscribe_template_template_content'), table_name='wx_msg_subscribe_template')
    op.drop_index(op.f('ix_wx_msg_subscribe_template_page'), table_name='wx_msg_subscribe_template')
    op.drop_index(op.f('ix_wx_msg_subscribe_template_miniprogram_state'), table_name='wx_msg_subscribe_template')
    op.drop_index(op.f('ix_wx_msg_subscribe_template_id'), table_name='wx_msg_subscribe_template')
    op.drop_index(op.f('ix_wx_msg_subscribe_template_entry'), table_name='wx_msg_subscribe_template')
    op.drop_table('wx_msg_subscribe_template')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_user_id'), table_name='users')
    op.drop_table('users')
    op.drop_table('test2')
    # ### end Alembic commands ###
