"""create wx_msg_subscribe_user table

Revision ID: 8b31aaf6e305
Revises: 6c12c4e740d1
Create Date: 2025-03-12 11:29:19.367514

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b31aaf6e305'
down_revision: Union[str, None] = '6c12c4e740d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wx_msg_subscribe_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('openid', sa.String(length=50), nullable=True),
    sa.Column('template_id', sa.String(length=50), nullable=True),
    sa.Column('subscribe_status', sa.String(length=50), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wx_msg_subscribe_user_id'), 'wx_msg_subscribe_user', ['id'], unique=True)
    op.create_index(op.f('ix_wx_msg_subscribe_user_openid'), 'wx_msg_subscribe_user', ['openid'], unique=True)
    op.create_index(op.f('ix_wx_msg_subscribe_user_subscribe_status'), 'wx_msg_subscribe_user', ['subscribe_status'], unique=True)
    op.create_index(op.f('ix_wx_msg_subscribe_user_template_id'), 'wx_msg_subscribe_user', ['template_id'], unique=True)
    op.create_index(op.f('ix_wx_msg_subscribe_user_user_id'), 'wx_msg_subscribe_user', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wx_msg_subscribe_user_user_id'), table_name='wx_msg_subscribe_user')
    op.drop_index(op.f('ix_wx_msg_subscribe_user_template_id'), table_name='wx_msg_subscribe_user')
    op.drop_index(op.f('ix_wx_msg_subscribe_user_subscribe_status'), table_name='wx_msg_subscribe_user')
    op.drop_index(op.f('ix_wx_msg_subscribe_user_openid'), table_name='wx_msg_subscribe_user')
    op.drop_index(op.f('ix_wx_msg_subscribe_user_id'), table_name='wx_msg_subscribe_user')
    op.drop_table('wx_msg_subscribe_user')
    # ### end Alembic commands ###
