"""auto migration

Revision ID: 8c2d8c824640
Revises: a177500d38c1
Create Date: 2025-03-10 15:42:53.302474

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '8c2d8c824640'
down_revision: Union[str, None] = 'a177500d38c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test2',
    sa.Column('test2_id', sa.Integer(), nullable=False),
    sa.Column('test2_name', sa.String(length=50), nullable=True),
    sa.Column('test2_age', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('test2_id')
    )
    op.drop_table('test')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test',
    sa.Column('test_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('test_name', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('test_age', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('test_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('test2')
    # ### end Alembic commands ###
