"""auto migration

Revision ID: 9cc952e6a3d0
Revises: 8b31aaf6e305
Create Date: 2025-03-12 14:14:17.770158

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9cc952e6a3d0'
down_revision: Union[str, None] = '8b31aaf6e305'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wx_msg_subscribe_template',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entry', sa.String(length=50), nullable=True),
    sa.Column('template_id', sa.String(length=50), nullable=True),
    sa.Column('template_name', sa.String(length=255), nullable=True),
    sa.Column('template_content', sa.String(length=255), nullable=True),
    sa.Column('page', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wx_msg_subscribe_template_entry'), 'wx_msg_subscribe_template', ['entry'], unique=True)
    op.create_index(op.f('ix_wx_msg_subscribe_template_id'), 'wx_msg_subscribe_template', ['id'], unique=True)
    op.create_index(op.f('ix_wx_msg_subscribe_template_page'), 'wx_msg_subscribe_template', ['page'], unique=True)
    op.create_index(op.f('ix_wx_msg_subscribe_template_template_content'), 'wx_msg_subscribe_template', ['template_content'], unique=True)
    op.create_index(op.f('ix_wx_msg_subscribe_template_template_id'), 'wx_msg_subscribe_template', ['template_id'], unique=True)
    op.create_index(op.f('ix_wx_msg_subscribe_template_template_name'), 'wx_msg_subscribe_template', ['template_name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wx_msg_subscribe_template_template_name'), table_name='wx_msg_subscribe_template')
    op.drop_index(op.f('ix_wx_msg_subscribe_template_template_id'), table_name='wx_msg_subscribe_template')
    op.drop_index(op.f('ix_wx_msg_subscribe_template_template_content'), table_name='wx_msg_subscribe_template')
    op.drop_index(op.f('ix_wx_msg_subscribe_template_page'), table_name='wx_msg_subscribe_template')
    op.drop_index(op.f('ix_wx_msg_subscribe_template_id'), table_name='wx_msg_subscribe_template')
    op.drop_index(op.f('ix_wx_msg_subscribe_template_entry'), table_name='wx_msg_subscribe_template')
    op.drop_table('wx_msg_subscribe_template')
    # ### end Alembic commands ###
