"""auto migration

Revision ID: ac71f30022c2
Revises: 4e9b0c59d1b1
Create Date: 2025-03-12 16:47:41.398729

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac71f30022c2'
down_revision: Union[str, None] = '4e9b0c59d1b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_wx_msg_subscribe_user_subscribe_status', table_name='wx_msg_subscribe_user')
    op.create_index(op.f('ix_wx_msg_subscribe_user_subscribe_status'), 'wx_msg_subscribe_user', ['subscribe_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wx_msg_subscribe_user_subscribe_status'), table_name='wx_msg_subscribe_user')
    op.create_index('ix_wx_msg_subscribe_user_subscribe_status', 'wx_msg_subscribe_user', ['subscribe_status'], unique=True)
    # ### end Alembic commands ###
