"""auto migration

Revision ID: d08b0937dbb9
Revises: d5b223309506
Create Date: 2025-03-12 16:54:46.992415

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'd08b0937dbb9'
down_revision: Union[str, None] = 'd5b223309506'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('wx_msg_subscribe_template', 'entry',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    op.alter_column('wx_msg_subscribe_template', 'template_id',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    op.alter_column('wx_msg_subscribe_template', 'template_name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('wx_msg_subscribe_template', 'template_content',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('wx_msg_subscribe_template', 'page',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('wx_msg_subscribe_template', 'miniprogram_state',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.drop_index('ix_wx_msg_subscribe_template_entry', table_name='wx_msg_subscribe_template')
    op.create_index(op.f('ix_wx_msg_subscribe_template_entry'), 'wx_msg_subscribe_template', ['entry'], unique=False)
    op.drop_index('ix_wx_msg_subscribe_template_miniprogram_state', table_name='wx_msg_subscribe_template')
    op.create_index(op.f('ix_wx_msg_subscribe_template_miniprogram_state'), 'wx_msg_subscribe_template', ['miniprogram_state'], unique=False)
    op.drop_index('ix_wx_msg_subscribe_template_page', table_name='wx_msg_subscribe_template')
    op.create_index(op.f('ix_wx_msg_subscribe_template_page'), 'wx_msg_subscribe_template', ['page'], unique=False)
    op.drop_index('ix_wx_msg_subscribe_template_template_content', table_name='wx_msg_subscribe_template')
    op.create_index(op.f('ix_wx_msg_subscribe_template_template_content'), 'wx_msg_subscribe_template', ['template_content'], unique=False)
    op.drop_index('ix_wx_msg_subscribe_template_template_id', table_name='wx_msg_subscribe_template')
    op.create_index(op.f('ix_wx_msg_subscribe_template_template_id'), 'wx_msg_subscribe_template', ['template_id'], unique=False)
    op.drop_index('ix_wx_msg_subscribe_template_template_name', table_name='wx_msg_subscribe_template')
    op.create_index(op.f('ix_wx_msg_subscribe_template_template_name'), 'wx_msg_subscribe_template', ['template_name'], unique=False)
    op.alter_column('wx_msg_subscribe_user', 'template_id',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    op.drop_index('ix_wx_msg_subscribe_user_template_id', table_name='wx_msg_subscribe_user')
    op.create_index(op.f('ix_wx_msg_subscribe_user_template_id'), 'wx_msg_subscribe_user', ['template_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wx_msg_subscribe_user_template_id'), table_name='wx_msg_subscribe_user')
    op.create_index('ix_wx_msg_subscribe_user_template_id', 'wx_msg_subscribe_user', ['template_id'], unique=True)
    op.alter_column('wx_msg_subscribe_user', 'template_id',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    op.drop_index(op.f('ix_wx_msg_subscribe_template_template_name'), table_name='wx_msg_subscribe_template')
    op.create_index('ix_wx_msg_subscribe_template_template_name', 'wx_msg_subscribe_template', ['template_name'], unique=True)
    op.drop_index(op.f('ix_wx_msg_subscribe_template_template_id'), table_name='wx_msg_subscribe_template')
    op.create_index('ix_wx_msg_subscribe_template_template_id', 'wx_msg_subscribe_template', ['template_id'], unique=True)
    op.drop_index(op.f('ix_wx_msg_subscribe_template_template_content'), table_name='wx_msg_subscribe_template')
    op.create_index('ix_wx_msg_subscribe_template_template_content', 'wx_msg_subscribe_template', ['template_content'], unique=True)
    op.drop_index(op.f('ix_wx_msg_subscribe_template_page'), table_name='wx_msg_subscribe_template')
    op.create_index('ix_wx_msg_subscribe_template_page', 'wx_msg_subscribe_template', ['page'], unique=True)
    op.drop_index(op.f('ix_wx_msg_subscribe_template_miniprogram_state'), table_name='wx_msg_subscribe_template')
    op.create_index('ix_wx_msg_subscribe_template_miniprogram_state', 'wx_msg_subscribe_template', ['miniprogram_state'], unique=True)
    op.drop_index(op.f('ix_wx_msg_subscribe_template_entry'), table_name='wx_msg_subscribe_template')
    op.create_index('ix_wx_msg_subscribe_template_entry', 'wx_msg_subscribe_template', ['entry'], unique=True)
    op.alter_column('wx_msg_subscribe_template', 'miniprogram_state',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('wx_msg_subscribe_template', 'page',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('wx_msg_subscribe_template', 'template_content',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('wx_msg_subscribe_template', 'template_name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('wx_msg_subscribe_template', 'template_id',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    op.alter_column('wx_msg_subscribe_template', 'entry',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    # ### end Alembic commands ###
