"""auto migration

Revision ID: ebc3134199c9
Revises: 75df7ee3a52c
Create Date: 2025-03-14 17:56:53.449785

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ebc3134199c9'
down_revision: Union[str, None] = '75df7ee3a52c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shows',
    sa.Column('show_id', sa.String(length=20), nullable=False, comment='演出全局唯一ID'),
    sa.Column('show_name', sa.String(length=100), nullable=False, comment='演出名称'),
    sa.Column('venue_city_name', sa.String(length=50), nullable=False, comment='场馆所在城市'),
    sa.Column('venue_name', sa.String(length=50), nullable=False, comment='场馆名称'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('show_id'),
    comment='演出主表'
    )
    op.create_index('idx_venue', 'shows', ['venue_city_name', 'venue_name'], unique=False)
    op.create_table('performances',
    sa.Column('perform_id', sa.String(length=20), nullable=False, comment='场次唯一ID'),
    sa.Column('show_id', sa.String(length=20), nullable=False, comment='关联演出ID'),
    sa.Column('perform_name', sa.String(length=100), nullable=False, comment='场次名称（含时间）'),
    sa.Column('perform_time', sa.DateTime(), nullable=True, comment='演出时间'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['show_id'], ['shows.show_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('perform_id'),
    comment='演出场次表'
    )
    op.create_index('idx_show_id', 'performances', ['show_id'], unique=False)
    op.create_table('user_show_monitors',
    sa.Column('monitor_id', sa.BigInteger(), autoincrement=True, nullable=False, comment='监控记录ID'),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('wx_token', sa.String(length=50), nullable=False, comment='用户微信openid'),
    sa.Column('show_id', sa.String(length=20), nullable=False, comment='关联演出ID'),
    sa.Column('deadline', sa.DateTime(), nullable=False, comment='监控截止日期'),
    sa.Column('is_active', sa.SmallInteger(), server_default=sa.text('1'), nullable=True, comment='是否有效（0-无效 1-有效）'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['show_id'], ['shows.show_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('monitor_id'),
    comment='用户监控主表'
    )
    op.create_index('idx_deadline', 'user_show_monitors', ['deadline'], unique=False)
    op.create_index('idx_show_user', 'user_show_monitors', ['show_id', 'wx_token'], unique=False)
    op.create_index('idx_wx_token', 'user_show_monitors', ['wx_token'], unique=False)
    op.create_table('ticket_prices',
    sa.Column('sku_id', sa.String(length=20), nullable=False, comment='票种唯一ID'),
    sa.Column('perform_id', sa.String(length=20), nullable=False, comment='关联场次ID'),
    sa.Column('price_id', sa.String(length=20), nullable=False, comment='价格体系ID'),
    sa.Column('price_name', sa.String(length=50), nullable=False, comment='价格显示名称'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['perform_id'], ['performances.perform_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('sku_id'),
    comment='票种表'
    )
    op.create_index('idx_perform_id', 'ticket_prices', ['perform_id'], unique=False)
    op.create_table('user_ticket_monitors',
    sa.Column('monitor_ticket_id', sa.BigInteger(), autoincrement=True, nullable=False, comment='监控票务ID'),
    sa.Column('user_show_monitor_id', sa.BigInteger(), nullable=False),
    sa.Column('perform_id', sa.String(length=20), nullable=False, comment='关联场次ID'),
    sa.Column('sku_id', sa.String(length=20), nullable=False, comment='关联票种ID'),
    sa.Column('is_notified', sa.Boolean(), nullable=True, comment='是否已通知'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['perform_id'], ['performances.perform_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sku_id'], ['ticket_prices.sku_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_show_monitor_id'], ['user_show_monitors.monitor_id'], ),
    sa.PrimaryKeyConstraint('monitor_ticket_id', 'perform_id', 'sku_id'),
    comment='用户票价监控表'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_ticket_monitors')
    op.drop_index('idx_perform_id', table_name='ticket_prices')
    op.drop_table('ticket_prices')
    op.drop_index('idx_wx_token', table_name='user_show_monitors')
    op.drop_index('idx_show_user', table_name='user_show_monitors')
    op.drop_index('idx_deadline', table_name='user_show_monitors')
    op.drop_table('user_show_monitors')
    op.drop_index('idx_show_id', table_name='performances')
    op.drop_table('performances')
    op.drop_index('idx_venue', table_name='shows')
    op.drop_table('shows')
    # ### end Alembic commands ###
